version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run:
          name: Install Python dependencies
          command: poetry install
      - run:
          name: Run tests
          command: make test
